version: "3.3"
services:
  palworld:
    build: .
    image: palworld
    tty: false
    stdin_open: false
    environment:
      STEAMCMD_APP_ID: "294420"
      STEAMCMD_SKIP: "true"
      UID: "${UID}"
      GID: "${GID}"
    network_mode: "host"
    volumes:
      - "./saves:/saves"
